import { getUserWorkspacePermissions } from '@/services/permissionService';

export function buildWorkspaceContextValue(ctx) {
  return {
    currentUser: ctx.currentUser,
    loading: ctx.loading,
    login: ctx.login,
    register: ctx.register,
    setUser: ctx.setUser,
    logout: ctx.logout,

    workspaces: ctx.workspaces,
    setWorkspaces: ctx.setWorkspaces,
    activeWorkspaceId: ctx.activeWorkspaceId,
    activeWorkspace: ctx.activeWorkspace,
    selectWorkspace: ctx.selectWorkspace,
    createWorkspace: ctx.createWorkspace,
    activeTeamId: ctx.activeTeamId,
    activeTeam: ctx.activeTeam,

    workspaceRole: ctx.workspaceRole,
    workspaceRoleLabels: ctx.workspaceRoleLabels,
    workspaceRoleColors: ctx.workspaceRoleColors,

    activeView: ctx.activeView,
    selectView: ctx.selectView,
    activeChannelId: ctx.activeChannelId,
    activeVoiceChannelId: ctx.activeVoiceChannelId,
    activeChannel: ctx.activeChannel,
    selectChannel: ctx.selectChannel,
    selectTeamChat: ctx.selectTeamChat,

    textChannels: ctx.textChannels,
    voiceChannels: ctx.voiceChannels,
    createChannel: ctx.createChannel,
    deleteChannel: ctx.deleteChannel,

    voiceParticipants: ctx.voiceParticipants,
    activeVoiceRecordings: ctx.activeVoiceRecordings,
    voiceRecords: ctx.voiceRecords,
    maxVoiceRecordingSizeBytes: ctx.maxVoiceRecordingSizeBytes,
    warningVoiceRecordingSizeBytes: ctx.warningVoiceRecordingSizeBytes,
    canAccessVoice: ctx.canAccessVoice,
    canRecordVoice: ctx.canRecordVoice,
    updateVoiceParticipantState: ctx.updateVoiceParticipantState,
    syncVoiceParticipant: ctx.syncVoiceParticipant,
    removeVoiceParticipant: ctx.removeVoiceParticipant,
    setVoiceChannelParticipants: ctx.setVoiceChannelParticipants,
    joinVoiceChannel: ctx.joinVoiceChannel,
    leaveVoiceChannel: ctx.leaveVoiceChannel,
    switchVoiceChannel: ctx.switchVoiceChannel,
    getCurrentUserVoiceChannel: ctx.getCurrentUserVoiceChannel,
    isCurrentUserInVoice: ctx.isCurrentUserInVoice,
    removeUserFromAllVoiceChannels: ctx.removeUserFromAllVoiceChannels,
    startVoiceRecording: ctx.startVoiceRecording,
    stopVoiceRecording: ctx.stopVoiceRecording,
    getActiveVoiceRecordingMetrics: ctx.getActiveVoiceRecordingMetrics,
    updateVoiceChannelPermissions: ctx.updateVoiceChannelPermissions,
    addTeamToVoiceChannel: ctx.addTeamToVoiceChannel,
    removeTeamFromVoiceChannel: ctx.removeTeamFromVoiceChannel,
    addUserToVoiceChannel: ctx.addUserToVoiceChannel,
    removeUserFromVoiceChannel: ctx.removeUserFromVoiceChannel,
    toggleVoiceChannelLock: ctx.toggleVoiceChannelLock,
    toggleVoiceRecordingPermission: ctx.toggleVoiceRecordingPermission,
    sendVoiceRecordToAI: ctx.sendVoiceRecordToAI,
    deleteVoiceRecord: ctx.deleteVoiceRecord,

    channelMessages: ctx.channelMessages,
    teamMessagesKey: ctx.teamMessagesKey,
    activeTeamMessages: ctx.activeTeamMessages,
    sendMessage: ctx.sendMessage,
    sendTeamMessage: ctx.sendTeamMessage,

    workspaceTasks: ctx.workspaceTasks,
    addWorkspaceTasks: ctx.addWorkspaceTasks,
    moveWorkspaceTask: ctx.moveWorkspaceTask,
    deleteWorkspaceTask: ctx.deleteWorkspaceTask,

    workspaceMeetings: ctx.workspaceMeetings,
    meetings: ctx.workspaceMeetings,
    setMeetings: ctx.setWorkspaceMeetings,
    createMeeting: ctx.createMeeting,
    deleteMeeting: ctx.deleteMeeting,
    uploadMeetingMock: ctx.uploadMeetingMock,
    analyzeMeetingWithAI: ctx.analyzeMeetingWithAI,
    processMeetingWithAI: ctx.processMeetingWithAI,
    reAnalyzeMeeting: ctx.reAnalyzeMeeting,
    updateSuggestedTask: ctx.updateSuggestedTask,
    updateMeetingSuggestion: ctx.updateMeetingSuggestion,
    toggleSuggestedTaskSelection: ctx.toggleSuggestedTaskSelection,
    removeMeetingSuggestion: ctx.removeMeetingSuggestion,
    createTasksFromSuggestions: ctx.createTasksFromSuggestions,
    createTasksFromMeeting: ctx.createTasksFromMeeting,
    getTasksByMeeting: ctx.getTasksByMeeting,

    workspaceMembers: ctx.workspaceMembers,
    updateMemberRole: ctx.updateMemberRole,
    removeMember: ctx.removeMember,

    workspaceTeams: ctx.workspaceTeams,
    canAccessTeam: ctx.canAccessTeam,
    createTeam: ctx.createTeam,
    updateTeam: ctx.updateTeam,
    deleteTeam: ctx.deleteTeam,
    addMemberToTeam: ctx.addMemberToTeam,
    removeMemberFromTeam: ctx.removeMemberFromTeam,
    assignTeamManager: ctx.assignTeamManager,

    invitations: ctx.invitations,
    userInvitations: ctx.userInvitations,
    sendInvitation: ctx.sendInvitation,
    acceptInvitation: ctx.acceptInvitation,
    declineInvitation: ctx.declineInvitation,
    showInvitations: ctx.showInvitations,
    setShowInvitations: ctx.setShowInvitations,

    createCustomRole: ctx.createCustomRole,

    can: ctx.can,
    canInWorkspace: ctx.canInWorkspace,
    getAllPermissions: () => {
      if (!ctx.activeWorkspace || !ctx.currentUser) return [];
      if (ctx.workspaceRole === 'OWNER') return 'all';
      return getUserWorkspacePermissions(ctx.activeWorkspace, ctx.currentUser.id);
    },

    onboarding: ctx.onboarding,
    initOnboarding: ctx.initOnboarding,
    completeOnboardingStep: ctx.completeOnboardingStep,
    dismissOnboarding: ctx.dismissOnboarding,

    activityFeed: ctx.activityFeed,
    addActivity: ctx.addActivity,

    trashItems: ctx.trashItems,
    restoreTrashItem: ctx.restoreTrashItem,
    permanentlyDeleteTrashItem: ctx.permanentlyDeleteTrashItem,

    aiNotifications: ctx.aiNotifications,
    addNotification: ctx.addNotification,
    markNotificationRead: ctx.markNotificationRead,
    markAllNotificationsRead: ctx.markAllNotificationsRead,
    workspaceNotificationsEnabled: ctx.workspaceNotificationsEnabled,
    workspaceNotificationSettings: ctx.workspaceNotificationSettings,
    setWorkspaceNotificationsEnabled: ctx.setWorkspaceNotificationsEnabled,
    toggleWorkspaceNotifications: ctx.toggleWorkspaceNotifications,

    toasts: ctx.toasts,
    showToast: ctx.showToast,
    dismissToast: ctx.dismissToast,

    showUserMenu: ctx.showUserMenu,
    setShowUserMenu: ctx.setShowUserMenu,
    showCreateChannel: ctx.showCreateChannel,
    setShowCreateChannel: ctx.setShowCreateChannel,
    showCreateWorkspace: ctx.showCreateWorkspace,
    setShowCreateWorkspace: ctx.setShowCreateWorkspace,
    showCreateTeam: ctx.showCreateTeam,
    setShowCreateTeam: ctx.setShowCreateTeam,
    showInviteMember: ctx.showInviteMember,
    setShowInviteMember: ctx.setShowInviteMember,
    showNotifications: ctx.showNotifications,
    setShowNotifications: ctx.setShowNotifications,
    notificationCount: ctx.notificationCount,
  };
}
