export const AWS_COST_ASSUMPTIONS = {
  region: 'us-east-1',
  transcribeUsdPerMinute: 0.024,
  bedrockInputUsdPerMillionTokens: 0.8,
  bedrockOutputUsdPerMillionTokens: 4,
  stepFunctionUsdPerStateTransition: 0.000025,
  s3StandardUsdPerGbMonth: 0.023,
  dynamodbUsdPerMillionWriteUnits: 1.25,
  averageInputTokensPerAudioMinute: 750,
  averageOutputTokensPerAudioMinute: 120,
  averageStateTransitionsPerMeeting: 8,
  platformOverheadUsdPerWorkspace: 3,
};

export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Free Pilot',
    priceUsdMonthly: 0,
    priceVndMonthly: 0,
    targetCustomer: 'Solo founders, students, and teams validating AI meeting notes before rollout.',
    businessOutcome: 'Capture a small number of meetings and prove that summaries can become reviewed tasks.',
    operatingModel: 'Manual manager review, limited history, no formal governance workflow.',
    includedAudioMinutesMonthly: 60,
    maxUploadMbPerFile: 50,
    maxMembers: 3,
    maxWorkspaces: 1,
    maxTeamsPerWorkspace: 1,
    meetingHistoryDays: 30,
    concurrentAiJobs: 1,
    voiceRecordingMinutesMonthly: 45,
    includedAiCreditsMonthly: 6,
    fairUsePolicy: 'Trial quota. AI processing stops at the monthly minute cap to protect AWS credits.',
    exportFormats: ['TXT summary', 'Task checklist'],
    workflowCapabilities: [
      'Upload audio or transcript',
      'Basic summary and suggested tasks',
      'Manual approval before task creation',
      'Starter meeting search for recent history',
    ],
    aiFeatures: [
      'Audio transcription',
      'Basic meeting summary',
      'Up to 10 suggested action items',
    ],
    support: 'Community docs and best-effort email.',
    security: [
      'Password account access',
      'Workspace owner role',
      'Basic file validation',
    ],
    governance: 'No SSO, no audit export, no custom retention.',
    overageUsdPerMinute: null,
    awsCostBufferMultiplier: 1.25,
    cta: 'Upgrade for longer meetings and team collaboration.',
  },
  {
    id: 'business',
    name: 'Business Ops',
    priceUsdMonthly: 99,
    priceVndMonthly: 2490000,
    targetCustomer: 'SMB teams running weekly operations, project reviews, and cross-functional standups.',
    businessOutcome: 'Turn recurring meetings into assigned work with searchable evidence and team-level accountability.',
    operatingModel: 'Workspace owners manage members, teams, retention, usage alerts, and manager-approved AI tasks.',
    includedAudioMinutesMonthly: 1200,
    maxUploadMbPerFile: 150,
    maxMembers: 20,
    maxWorkspaces: 3,
    maxTeamsPerWorkspace: 10,
    meetingHistoryDays: 365,
    concurrentAiJobs: 2,
    voiceRecordingMinutesMonthly: 600,
    includedAiCreditsMonthly: 120,
    fairUsePolicy: 'Includes a healthy operations quota. Overage is billed per processed minute after quota.',
    exportFormats: ['TXT summary', 'CSV task export', 'Meeting evidence report', 'Slack/Notion-ready recap'],
    workflowCapabilities: [
      'Speaker labels and searchable transcript history',
      'Decision, risk, and action-item extraction',
      'Task evidence with timestamp/source quote',
      'Workflow handoff to task board and team channels',
      'Usage alerts at 70, 85, and 95 percent quota',
    ],
    aiFeatures: [
      'Transcription with speaker labels',
      'Summary, decisions, risks, and task extraction',
      'Task evidence with timestamp/source quote',
      'Searchable meeting history',
    ],
    support: 'Priority email support, target response within 1 business day.',
    security: [
      'Workspace roles and permissions',
      'Permission audit UI',
      'Data retention controls',
      'Private workspace invites',
    ],
    governance: 'Admin dashboard, export-ready meeting records, and usage alerts.',
    overageUsdPerMinute: 0.09,
    awsCostBufferMultiplier: 1.45,
    cta: 'Scale minutes, members, retention, and governance.',
  },
  {
    id: 'enterprise',
    name: 'Enterprise Governance',
    priceUsdMonthly: null,
    priceVndMonthly: null,
    targetCustomer: 'Departments and regulated companies that need governance, procurement, and custom capacity.',
    businessOutcome: 'Standardize meeting intelligence across departments with compliance-ready controls and analytics.',
    operatingModel: 'Central admin policy, audit export, custom retention, SSO-ready access, and SLA-backed operations.',
    includedAudioMinutesMonthly: 6000,
    maxUploadMbPerFile: 350,
    maxMembers: Infinity,
    maxWorkspaces: Infinity,
    maxTeamsPerWorkspace: Infinity,
    meetingHistoryDays: 2555,
    concurrentAiJobs: 6,
    voiceRecordingMinutesMonthly: 3000,
    includedAiCreditsMonthly: 600,
    fairUsePolicy: 'Custom committed-use contract with negotiated pooled credits, overage, and SLA.',
    exportFormats: ['CSV/XLSX exports', 'Audit log export', 'Department analytics pack'],
    workflowCapabilities: [
      'Business plan workflow plus department analytics',
      'Custom AI templates for meeting types',
      'PII-aware processing option and legal hold',
      'SAML/SSO-ready access policy and audit export',
    ],
    aiFeatures: [
      'All Business AI features',
      'Custom AI prompts and templates',
      'PII-aware processing option',
      'Department-level analytics',
      'Enterprise search/export workflow',
    ],
    support: 'Priority support, onboarding, and custom SLA.',
    security: [
      'SSO/SAML-ready architecture',
      'MFA policy via Cognito',
      'Audit log export',
      'Custom retention and legal hold',
      'Dedicated AWS account option',
    ],
    governance: 'Custom contracts, procurement, data residency, and compliance review.',
    overageUsdPerMinute: 0.075,
    awsCostBufferMultiplier: 1.7,
    cta: 'Contact sales for custom capacity and SLA.',
  },
];

export const DEFAULT_PLAN_ID = 'free';

export const PLAN_ORDER = ['free', 'business', 'enterprise'];
