'use client';

export const VOICE_AUDIO_CONFIG = {
  noiseSuppressionMode: 'dtln-ai',
  browserEchoCancellation: true,
  browserNoiseSuppression: true,
  browserAutoGainControl: true,
  sampleRate: 48000,
  channelCount: 1,
  sampleSize: 16,
  latency: 0.02,
  highpassEnabled: true,
  highpassFrequency: 85,
  noiseGateEnabled: true,
  noiseGateThreshold: 0.012,
  noiseGateReduction: 0.35,
  noiseGateAttackMs: 8,
  noiseGateReleaseMs: 120,
  gainEnabled: true,
  micGain: 1.45,
  localMicMakeupGain: 1.5,
  recordingLocalGain: 1.6,
  recordingRemoteGain: 1,
  recordingMasterGain: 1,
  maxRecordingGain: 1.8,
  mixedRoomMinHeadroom: 0.65,
  compressorEnabled: true,
  compressorThreshold: -24,
  compressorKnee: 30,
  compressorRatio: 5,
  compressorAttack: 0.003,
  compressorRelease: 0.25,
  limiterEnabled: true,
  limiterThreshold: -6,
  senderMaxBitrate: 64000,
  dtx: 'disabled',
  senderDtx: 'disabled',
  remoteDefaultVolume: 1,
};

export const VOICE_NOISE_SUPPRESSION_MODES = [
  'off',
  'browser-only',
  'browser-plus-webaudio',
  'dtln-ai',
  'future-rnnoise',
  'future-krisp',
];
