/**
 * Cognito JWT Verification for Lambda handlers
 *
 * Verifies access tokens from Amazon Cognito user pools.
 * In development (mock mode), falls back to decoding the local mock token format.
 *
 * @module lambdas/shared/cognitoAuth
 */

import { createHash, timingSafeEqual } from 'node:crypto';

const { ENVIRONMENT, COGNITO_USER_POOL_ID, COGNITO_CLIENT_ID, AWS_REGION } = process.env;
const IS_MOCK = ENVIRONMENT === 'development' || !COGNITO_USER_POOL_ID;

/**
 * @typedef {Object} AuthUser
 * @property {string} userId - User's unique ID (sub)
 * @property {string} email - User's email
 * @property {string} role - User's role (ADMIN|MANAGER|EMPLOYEE)
 * @property {string|null} departmentId - User's department
 * @property {string|null} workspaceId - User's active workspace
 */

/**
 * Verify a Cognito JWT access token or mock token.
 *
 * In production:
 *   - Downloads and caches Cognito JWKS
 *   - Verifies token signature, expiry, issuer, and audience
 *
 * In development (mock):
 *   - Decodes base64 payload (matching frontend withAuth mock format)
 *
 * @param {string} token - Bearer token (without "Bearer " prefix)
 * @returns {Promise<AuthUser>}
 * @throws {Error} If token is invalid
 */
export async function verifyToken(token) {
  if (!token) {
    throw new AuthError('No token provided', 'AUTH_REQUIRED');
  }

  if (IS_MOCK) {
    return verifyMockToken(token);
  }

  return verifyCognitoToken(token);
}

/**
 * Verify a mock base64-encoded token (development mode).
 * Matches the format generated by frontend's generateMockToken().
 *
 * @param {string} token
 * @returns {Promise<AuthUser>}
 */
async function verifyMockToken(token) {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) {
      throw new Error('Invalid token format');
    }

    const payload = JSON.parse(
      Buffer.from(parts[1], 'base64').toString('utf-8')
    );

    // Basic expiry check (optional for mock)
    if (payload.exp && payload.exp * 1000 < Date.now()) {
      throw new Error('Token expired');
    }

    return {
      userId: payload.sub || payload.userId,
      email: payload.email || '',
      role: payload.role || 'EMPLOYEE',
      departmentId: payload.departmentId || null,
      workspaceId: payload.workspaceId || null,
    };
  } catch (err) {
    throw new AuthError(
      err.message === 'Token expired' ? 'Token expired' : 'Invalid token',
      'AUTH_INVALID_TOKEN'
    );
  }
}

/**
 * Verify a real Cognito JWT token against the user pool's JWKS.
 *
 * @param {string} token
 * @returns {Promise<AuthUser>}
 */
async function verifyCognitoToken(token) {
  try {
    // In a real implementation, this would:
    // 1. Parse the JWT header to get the key ID (kid)
    // 2. Fetch the JWKS from Cognito's JWKS endpoint
    // 3. Use the matching key to verify the signature
    // 4. Validate claims: iss, aud/ client_id, token_use, exp

    const jwksUrl = `https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json`;

    // Fetch JWKS (with caching — in production use a proper JWKS client)
    const jwks = await fetchWithCache(jwksUrl);

    // Decode token header to get kid
    const header = JSON.parse(
      Buffer.from(token.split('.')[0], 'base64').toString('utf-8')
    );

    // Find matching key
    const key = jwks.keys.find((k) => k.kid === header.kid);
    if (!key) {
      throw new Error('No matching JWK key found');
    }

    // Convert JWK to PEM and verify (simplified — use jose or jsonwebtoken library)
    // In practice: use `jose` library's jwtVerify() for production

    const payload = JSON.parse(
      Buffer.from(token.split('.')[1], 'base64').toString('utf-8')
    );

    // Validate standard claims
    const expectedIssuer = `https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}`;
    if (payload.iss !== expectedIssuer) {
      throw new Error('Invalid issuer');
    }
    if (payload.token_use !== 'access') {
      throw new Error('Invalid token use — expected access token');
    }
    if (payload.client_id !== COGNITO_CLIENT_ID && payload.aud !== COGNITO_CLIENT_ID) {
      throw new Error('Invalid audience');
    }
    if (payload.exp && payload.exp * 1000 < Date.now()) {
      throw new Error('Token expired');
    }

    return {
      userId: payload.sub,
      email: payload.email || payload['cognito:email'] || '',
      role: extractRole(payload),
      departmentId: payload['custom:departmentId'] || null,
      workspaceId: payload['custom:workspaceId'] || null,
    };
  } catch (err) {
    throw new AuthError(
      err.message || 'Invalid token',
      'AUTH_INVALID_TOKEN'
    );
  }
}

/**
 * Extract the user's role from Cognito token custom attributes.
 * Defaults to EMPLOYEE if not set.
 *
 * @param {Object} payload - Decoded JWT payload
 * @returns {string}
 */
function extractRole(payload) {
  const role = payload['custom:role'] || payload.role;
  if (['ADMIN', 'MANAGER', 'EMPLOYEE'].includes(role)) {
    return role;
  }
  return 'EMPLOYEE';
}

// ─── JWKS Cache ───────────────────────────────────────
const jwksCache = new Map();
const JWKS_CACHE_TTL = 3600_000; // 1 hour

async function fetchWithCache(url) {
  const cached = jwksCache.get(url);
  if (cached && cached.expiresAt > Date.now()) {
    return cached.data;
  }
  const response = await fetch(url);
  const data = await response.json();
  jwksCache.set(url, { data, expiresAt: Date.now() + JWKS_CACHE_TTL });
  return data;
}

// ─── Auth Error ────────────────────────────────────────
export class AuthError extends Error {
  /**
   * @param {string} message
   * @param {string} code - Error code (AUTH_REQUIRED, AUTH_INVALID_TOKEN, FORBIDDEN)
   */
  constructor(message, code = 'AUTH_ERROR') {
    super(message);
    this.name = 'AuthError';
    this.statusCode = code === 'AUTH_REQUIRED' ? 401 : code === 'FORBIDDEN' ? 403 : 401;
    this.code = code;
    this.isOperational = true;
  }
}

// ─── Middleware ────────────────────────────────────────

/**
 * Lambda middleware: verify token and attach user to event.
 * Usage: wrap your Lambda handler with this.
 *
 * @param {Function} handler - (event, context) => Promise<{ statusCode, body }>
 * @param {Object} [options]
 * @param {string[]} [options.roles] - Required roles. Empty = any authenticated user.
 * @returns {Function}
 */
export function withAuth(handler, options = {}) {
  return async (event, context) => {
    try {
      const token = extractToken(event);
      const user = await verifyToken(token);

      // Role-based authorization
      if (options.roles && options.roles.length > 0) {
        if (!options.roles.includes(user.role)) {
          return apiResponse(403, {
            success: false,
            error: 'FORBIDDEN',
            message: 'Insufficient permissions',
          });
        }
      }

      // Attach user to event for downstream use
      event.authUser = user;

      return await handler(event, context);
    } catch (err) {
      if (err instanceof AuthError) {
        return apiResponse(err.statusCode, {
          success: false,
          error: err.code,
          message: err.message,
        });
      }
      console.error('[withAuth] Unexpected error:', err);
      return apiResponse(500, {
        success: false,
        error: 'INTERNAL_ERROR',
        message: 'Internal server error',
      });
    }
  };
}

/**
 * Extract Bearer token from API Gateway event.
 * Supports: Authorization header, or event.auth.token (for custom authorizer)
 *
 * @param {Object} event - API Gateway proxy event
 * @returns {string|null}
 */
function extractToken(event) {
  // API Gateway REST API (v1) — headers are in event.headers
  const authHeader =
    event.headers?.Authorization ||
    event.headers?.authorization ||
    event.auth?.token ||
    '';

  if (authHeader.startsWith('Bearer ')) {
    return authHeader.slice(7);
  }
  return authHeader || null;
}

// ─── Response Helper ──────────────────────────────────

/**
 * Create a consistent API Gateway response.
 *
 * @param {number} statusCode
 * @param {Object} body
 * @returns {{ statusCode: number, headers: Object, body: string }}
 */
export function apiResponse(statusCode, body) {
  return {
    statusCode,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET,POST,PATCH,DELETE,OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type,Authorization',
    },
    body: JSON.stringify(body),
  };
}

export default { verifyToken, withAuth, AuthError, apiResponse };
